- error.zig
- sqlite.zig
Maps all error codes, except the unused ones.
Fixes #8
> Map errors

- README.md
- sqlite.zig
Add the ability to read a column into a pointer value
> Read pointers

- .builds/alpine-edge-amd64.yml
- .builds/debian-stable-aarch64.yml
- .builds/debian-stable-amd64.yml
- .builds/freebsd-latest-amd64.yml
- .github/workflows/main.yml
- build.zig
- sqlite.zig
- sqlite3.h
> embed sqlite source code

- build.zig
- query.zig
- sqlite.zig
Implement [incremental blob io](https://sqlite.org/c3ref/blob_open.html)
> implement incremental blob io

- README.md
- sqlite.zig
Introduce ways to get failure diagnostics
> add a way to get diagnostics

- sqlite.zig
Looking at the [PRAGMA documentation](https://sqlite.org/pragma.html) I see three kinds of PRAGMA statements:
* the form `PRAGMA foo = value;` which sets a single value
* the form `PRAGMA foo;` which returns a single value
* the form `PRAGMA foobar(...);` which is a function returning one or more rows, each row having different columns depending on the function.
PRAGMA functions are out of scope for now, I don't know how best to handle them.
This PR aims to simplify the API of `pragmaAlloc` and `pragma`: since the argument is already comptime-only, using a `[]const u8` doesn't have much impact because the caller can just use a string literal.
> replace the pragma argument with a nullable string

- sqlite.zig
e.g. if I have a result I know is exactly 10 bytes.
> Allow reading into static size arrays as long as size matches

- sqlite.zig
> modify exec to take a QueryOptions

- sqlite.zig
some documentation improvements on `Db.Mode`, `Db.OpenFlags`, `ZeroBlob` and `Db.openBlob`.
> Improve doc

- .github/workflows/main.yml
- .gitignore
- README.md
- sqlite.zig
Ran into some small bugs while getting started. This PR contains fixes for those issues.
> Various fixes

- README.md
> readme: fix git submodule setup instructions

- sqlite.zig
`DynamicQuery` didn't handle all functions properly
> A handful of tiny fixes.

- sqlite.zig
- add a test binding an empty slice to a text column
- fix readArray when reading zero-length blob
Closes #68
> debug empty slice

- sqlite.zig
> fix fuzzer found crash

- README.md
- sqlite.zig
This is the first part of adding support for [user-defined functions](https://www.sqlite.org/c3ref/create_function.html).
This PR only implements scalar functions, aggregate functions will come later.
Partly addresses #27
> add createScalarFunction to create a user-defined scalar function

- sqlite.zig
Add the ability to create [custom SQL aggregate functions](https://www.sqlite.org/appfunc.html#executive_summary)
> Add the ability to create custom aggregate functions

- query.zig
- sqlite.zig
It's currently impossible to use an optional type in a bind marker to enforce typing even though binding an optional type works just fine.
This PR fixes this.
> allow optional types in the bind marker type info

- sqlite.zig
The old way of working was that we always passed the user context as
first argument to both `step` and `finalize` functions and the caller
had no way of getting the [aggregate context](http://www3.sqlite.org/c3ref/aggregate_context.html) from
SQLite.
Now both `step` and `finalize` functions must have a first argument of type `FunctionContext`:
```zig
fn step(fctx: FunctionContext, input: u32) void {
var ctx = fctx.aggregateContext(*u32) orelse return;
ctx.* += input;
}
fn finalize(ctx: *u32) u32 {
var ctx = fctx.aggregateContext(*u32) orelse return 0;
return ctx.sum;
}
```
Fixes #89
> fix createAggregateFunction

- errors.zig
> add greaterThanOrEqualsTo

- sqlite.zig
Some tests assumed the database is empty which is not the case if we run the tests like this:
```
zig build test -Din_memory=false -Ddbfile=/tmp/my.db
```
Fixes #106
> Make tests work when using the same database file

- sqlite.zig
See https://github.com/ziglang/zig/pull/13930
> Update for latest Zig builtin renames

- c/sqlite3.h
Update sqlite to 3.43.1 for the [fixes and improvements](https://www.sqlite.org/releaselog/3_43_1.html) it provides.
No Zig changes so I did not add any tests.
> update sqlite to 3.43.1

- build.zig
> fix: keep up with zig master

- .github/workflows/main.yml
- build.zig
- query.zig
- sqlite.zig
- vtab.zig
Also some major refactoring around the query parsing state.
> fix for latest zig

- build.zig
it looks like zig 0.12 shipped with both `b.path()` and `.{ .path = "..."}` ways to construct a LazyPath, however post-0.12, the latter is completely removed (well, you could use `.src_path`, but that's discouraged).
I'm PR'ing this as the change _should_ be compatible with both 0.12 and master branch at the same time (I'm having to do some experiments with zig master)
> use b.path API when appropiate

- query.zig
- sqlite.zig
> Reuse field for binding

- .github/workflows/main.yml
> ci: run with ubuntu 24.04

- build.zig
I don't see any point using the system provided sqlite3 library. By using the bundled source code we simplify things and we get a more consistent setup: all platforms use the same sqlite source code.
> always use the bundled sqlite source

- sqlite.zig
error.Workaround was being returned due to
https://github.com/ziglang/zig/issues/5149. This has been fixed. Remove the error and todo items
> zig: remove workaround for ziglang#5149

- .github/workflows/main.yml
`goto-bus-stop/setup-zig` is unmaintained, change to `mlugg/setup-zig`.
> ci: change unmaintained action

- zig.mod
https://spdx.org/licenses/blessing.html
> zig.mod: define sqlite license
