README.md
sqlite.zig

Stmt.oneAlloc, Db.oneAlloc and Iterator.nextAlloc do the same thing as
Stmt.one, Db.one, Iterator.next respectively but they can allocate
memory.
This is useful when reading TEXT or BLOB columns because if you can't
allocate memory the only way to read these types is with an array which
means you must have an idea of the maximum size of the column.

Split allocating from non-allocating methods

---

sqlite.zig

Allow binding pointers which gives us two things:
* we can bind string literals which are technically pointers to arrays
* we can handle `[]const u8` and `[]u8` in the `.Pointer` switch arm
Fixes #13

Bind string literal

---

.builds/alpine-edge-amd64.yml
.builds/debian-stable-amd64.yml
.builds/freebsd-latest-amd64.yml
.github/workflows/main.yml
build.zig

Define the test targets in `build.zig` for a given OS and use that by default when running `zig build test`.
Also use QEMU to run the non-native tests.

Rework test runner script

---

sqlite.zig

`prepare` and `prepareWithDiags` parse the query at comptime in the
return type definition.
This exceeds the branch quota since https://github.com/ziglang/zig/commit/b11ac9c5bfb4048eb4aa561f8b3b058a76787f7e.
Use a block and `@setEvalBranchQuota` to work around this.
Fixes #30.

set the eval branch quota in the return type block

---

.github/workflows/main.yml

While the syntax seems OK and the correct steps are run, the build fails because of [this issue](https://github.com/vrischmann/zig-sqlite/runs/1757362032?check_suite_focus=true).

Add Windows to the CI

---

.builds/alpine-edge-amd64.yml
.builds/debian-stable-amd64.yml

For builds running in a x86_64 VM it should be work fine to run the tests with qemu.

ci: run the tests with qemu too

---

.builds/alpine-edge-amd64.yml
.builds/debian-stable-aarch64.yml
.builds/debian-stable-amd64.yml
.builds/freebsd-latest-amd64.yml
.github/workflows/main.yml
build.zig

Uses the GitHub runner so we can only test for `x86_64` at this time.

enable CI for macOS

---

sqlite.zig

we only need `anytype` options in the private `readXYZ` functions, the public API can avoid using them entirely.
Also fail with a more explicit error if the `allocator` field is not present in the options when it's mandatory.

stop using anytype for options

---

query.zig

fix incorrect bind marker detection inside strings by adding a new state when seeing a `'` or `"`

fix incorrect bind marker detection inside strings

---

query.zig

Both `identifier` and `identifier_type` in `BindMarker` are unused; remove them and clean up the parsing.

Cleanup query parsing

---

sqlite.zig

Fixes for https://github.com/ziglang/zig/pull/10766

fix sentinel

---

build.zig

This makes compilation fail instead of linking if we were to use something not supported by the system library when running tests.

only include the 'c' directory if we're using the bundled sqlite code

---

sqlite.zig

`sqlite3_error_offset` API [introduced on 3.38.0](https://www.sqlite.org/releaselog/3_38_2.html):
> Added the [sqlite3_error_offset()](https://www.sqlite.org/c3ref/errcode.html) interface, which can sometimes help to localize an SQL error to a specific character in the input SQL text, so that applications can provide better error messages.

add error offsets to DetailedError

---

sqlite.zig

When using `execDynamic`, you can have a runtime-known number of parameters in the query, however the current way of binding the parameters requires the values to be comptime-known.
This PR allows slices of form `[]T` to be passed as the `values` parameter, binding it to the statement with a runtime loop instead. Not sure how I should approach setting the `field_name` parameter to bindField, as it is comptime (so I'm just setting it to empty string). Any suggestions?
This was manually tested, but if this idea moves forward on being upstreamed, I plan to add it to the test suite.

Bind runtime slices to queries

---

sqlite.zig

This PR adds `Db.runMulti()`, which wraps statement prepare/execution in a loop so that it can process multiple statements from a single query string. SQLite enables this to happen via the `pzTail` argument in `sqlite_prepare` family of functions.
If this function is not welcome, this PR can be reduced to only enabling `pzTail` usage through `QueryOptions`, since with that the logic of `runMulti` can be moved over to library users.

Run multiple statements in a single query

---

sqlite.zig

Example: [We aren't exposing the sqlite backup functions](https://github.com/lun-4/awtfdb/blob/mistress/src/main.zig#L208), but it would be a waste to require the library user to copy-paste `errorFromResultCode`'s implementation.

Make errorFromResultCode public

---

query.zig
sqlite.zig

Closes #77 with a hacky solution: By making `ParsedQuery` generic on the length of the query, and then with a new `ParsedQueryFromString` helper, to prevent repetition from `ParsedQuery(query.len).from(query)`. Was not ready to change business logic all that much, but removing `from()` and putting it in the type initializer would be a nicer solution, it can be done if that approach is welcome.

Support any size for prepare() queries on comptime

---

errors.zig
sqlite.zig

Specifically:
* some error codes are only available with SQLite >= 3.22.0
* `SQLITE_DIRECTONLY` is only available since SQLite 3.30.0
If a user uses the bunded source code it's never going to be a problem but this can matter if they use the system sqlite.

Fix compilation with old SQLite versions

---

c.zig
errors.zig
sqlite.zig

After some testing it turns out we need at least SQLite 3.21.0 to
compile.
We _could_ work around this and make zig-sqlite work with older SQLite
versions but I don't think it's necessary because:
* "old" distributions like Debian Buster, RHEL 8 ship with SQLite >
3.21.0
* in any case if people want to build for OSes where SQLite is too old
they can use the bundled source code.

require SQLite >= 3.21.0

---

README.md

Hello, thank you for a fantastic library. I could not build with bundled sqlite3 following to current readme. Change some build api usage resolves this issue. My Zig version is `0.9.1` from latest release.

change some build api usage for building bundled sqlite3

---

.github/workflows/main.yml
build.zig
c.zig
c/loadable-ext-sqlite3.h
c/loadable-ext-sqlite3ext.h
c/loadable_extension.zig
c/sqlite3ext.h
examples/zigcrypto.zig
examples/zigcrypto_test.zig
tools/preprocess_files.zig

Add the ability to build a loadable extension (with `.load myextension.so` for example).
Buliding a loadable extension is problematic with Zig because the way sqlite3ext.h works is that it redefines the sqlite API with defines, like this:
```c
#define sqlite3_open_v2 sqlite3_api->open_v2
```
This is not supported by `translate-c`, I looked into ways to make it work but it's not straightforward:
* if there's already a definition for a function the aliasing macros won't do anything: `translate-c` keeps generating the code for the function defined in sqlite3.h
* even if there's no definition already, the code generated will fail to compile because it references the variable `sqlite3_api` which is not defined
* and even _if_ the `sqlite3_api` is defined before, the generated code fails to …

Loadable extension

---

helpers.zig
sqlite.zig
test.zig
vtab.zig

Initial work on virtual tables. The goal is to be able to easily create virtual tables using Zig and expose as little as possible of the C-ism of the raw sqlite interface.
Currently implementing a virtual table is done by providing a `Table` type which must implement the following:
```
const Cursor = <cursor type ...>
const InitError = error{...};
const BuildBestIndexErrror = error{...};
fn init(allocator: mem.Allocator, diags: *sqlite.vtab.VTabDiagnostics) InitError!*Table
fn deinit(table: *Table, allocator: mem.Allocator) void
fn buildBestIndex(table: *Table, diags: *sqlite.vtab.VTabDiagnostics, builder: *sqlite.vtab.BestIndexBuilder) BuildBestIndexError!void
```
The cursor type must implement the following:
```
const InitError = error{...};
const NextError = error{...};
const …
```

Virtual tables

---

sqlite.zig

not needed as we always prepare a dynamic statement

drop comptime from execMulti query

---

sqlite.zig

Fixes the following error:
```
sqlite.zig:343:50: error: expected type '[*c]const u8', found '[:0]const u8'
const result = c.sqlite3_open_v2(path, &db, flags, null);
^~~~
```

Fix compile error with Zig 0.10.0

---

build.zig
sqlite.zig
tools/preprocess_files.zig

Now the correct build APIs and `@memset` builtin are used.
Unfortunately `@cImport` fails for `aarch64` and `riscv64` targets, but I'm not sure how to fix this.
Not sure if I did this right so feel free to let me know

Fix build failures on latest Zig

---

sqlite.zig

Adds support for packed structs to be used as a column type backed by their int type without having to manually add the readField/bindField methods

support packed structs as columns backed by their int type

---

sqlite.zig

fixes the TODO and adds a proper escape hatch for when readField for stringly enums fails

readField remove unreachable and support default value in string backed enums

---

sqlite.zig

Statement.all already does so this patch puts in sync with that. If you prefer an `allAlloc` instead I can make a follow-up patch.

DynamicStatement.all: use iteratorAlloc

---

build.zig

Fixes the test build step issue I was having on Mac OS X. May also fix for others. Depends on #133.
Output on Mac OS X 13.x:
```
❯ zig build test -Din_memory=true --summary all
Build Summary: 5/5 steps succeeded; 52/52 tests passed
test success
└─ run x86_64-native-Debug-multi 52 passed 184ms MaxRSS:5M
└─ zig test x86_64-native-Debug-multi Debug x86_64-native success 3s MaxRSS:322M
├─ zig build-lib sqlite Debug x86_64-native success 5s MaxRSS:496M
└─ options success
```
Build changes only, so no new tests

Fix test build step for Mac OS X

---

vtab.zig

Not sure what's going on with the name mangling introduced in https://github.com/ziglang/zig/commit/9ea2076663730ab6ac9cad5cb5f84e58198d4d95 but we don't actually have to specify the type of the variable here.
Remove it so that we don't have to care.

Don't specify the type of the variable

---

build.zig.zon
c/sqlite3.h
c/sqlite3ext.h
query.zig
sqlite.zig
test.zig
vtab.zig

* Mostly updated to 3.44.0
* Some redundant changes already merged due to new Zig master throwing errors for `var` instead of `const` if the variable didn't change
* Changed `comptime var x = y` to `const x = comptime y`
- I've tested on my local environment.

Update to sqlite 3.44.0

---

query.zig
sqlite.zig

The function std.mem.copy was removed (see this link for details https://github.com/ziglang/zig/pull/18143).
I believe this should lead to the same results.
Edit: Another solution could be to use @memcpy.
I didn't write any tests for it, I only this branch again in my project and it compiles again and works for what I do.

Fix for deprecated std.mem.copy

---

query.zig

Supports the [] and ` identifiers in the query. https://sqlite.org/lang_keywords.html
Parses name of bind markers and will not count duplicated named bind markers.

Improvements to ParsedQuery

---

query.zig
sqlite.zig

Add distinct EmptyQuery error so execMulti can be run on .sql schema files with  `@embedFile` for example.
Fix the zig fmt errors in query.zig

Add distinct EmptyQuery error / Fix zig fmt on query.zig

---

build.zig

computeTestTargets returns reference to a function local scope variable which goes out of scope once the function returns.
When cross compiling the build panics as it accesses garbage memory.

build.zig: fix invalid reference

---

build.zig

With the recent Zig build system changes, Modules now work much like CMake library targets, in that settings applied to one module are applied to any other module which imports that module as a dependency.  For example, with my current changes, I'm able to do the following (at least for my use case):
```zig
// Example setup in build.zig
const sqlite = b.dependency("sqlite", .{
.target = target,
.optimize = optimize,
.use_bundled = true,
});
exe.root_module.addImport("sqlite", sqlite.module("sqlite"));
// Note that we no longer need to access and link to the "sqlite" artifact,
// nor add any include directories
```

build.zig: Configure module to be used downstream

---

.github/workflows/main.yml
build.zig
c.zig
c/loadable_extension.zig
c/workaround.c
c/workaround.h
helpers.zig
sqlite.zig

On some architectures `SQLITE_TRANSIENT` is translated in such a way that it fails to compile, see https://github.com/ziglang/zig/issues/15893
This PR works around this problem by using a C function to return the proper destructor type.

Workaround SQLITE_TRANSIENT

---

build.zig
sqlite.zig
vtab.zig

This PR adds the ability to enable SQLite features (at this point only `fts5`) via build system options and in doing so allows customising SQLite features without resorting to vendoring (as per https://github.com/vrischmann/zig-sqlite?tab=readme-ov-file#using-the-bundled-sqlite-source-code-file).
This means for example you can take the example of installation via the official package manager (https://github.com/vrischmann/zig-sqlite?tab=readme-ov-file#official-package-manager) and simply add, e.g., `.fts5 = true` to the options to enable full text search:
```zig
const sqlite = b.dependency("sqlite", .{
.target = target,
.optimize = optimize,
.fts5 = true,
});
exe.root_module.addImport("sqlite", sqlite.module("sqlite"));
// links the bundled sqlite3, so leave this out if you link the …
```

Enable features without vendoring

---

build.zig

The 32-bit Windows target currently has a miscompilation which was causing these tests to fail: https://github.com/ziglang/zig/issues/20047
Should fix the Windows CI failure

Disable x86-windows tests due to Zig miscompilation

---

README.md

Hello there, Really nice repo you got here. I'm just tweaking some documentation here. 
I am running zig version `0.14.0-dev.2051+b1361f237`.
Which is ahead of 0.13, but you would also be able to do my method here on 0.13 as well. So I think my pr is valid.
`std.mem.spanZ` is no longer in the standard. Found an alternate way to run the example. Updating readme for the next guy. 
Just a 2 line change to the README.md.

fixup README.md

---

sqlite.zig
vtab.zig

A recent master version of Zig broke things in the C translated code for sqlite, specifically in the pointer to the tail of the query in `sqlite3_prepare_v3`.
Instead of just fixing it somehow I decided to rework `execMulti` (which is the only code that needs the tail pointer) because I wasn't happy with exposing that awful raw C-pointer type to the user in `QueryOptions`.
Now we keep the tail pointer local to `execMulti`.

Fix latest zig

---

sqlite.zig

Resolves this compilation error hit when updating a 0.13 project to master. (No further testing was done as there are other issues in my project preventing successful compilation on master.)
```
/Users/matthias/.cache/zig/p/12204ecfb22b7109dd3400cbdae8885e31fc653f33424bf35fe5fa21ceeadc90fcf8/sqlite.zig:1683:66: error: no field named 'Int' in enum '@typeInfo(builtin.Type).@"union".tag_type.?'
} else if (@typeInfo(FieldType.BaseType) == .Int) {
~^~~
/Users/matthias/bin/lib/std/builtin.zig:557:18: note: enum declared here
pub const Type = union(enum) {
^~~~~
```

Update some missed Int -> int

---

zig.mod

finally getting around to updating https://github.com/nektro/zig-zorm to 0.13 (i know 😅) and got the following error before applying this patch:
```
error: ld.lld: undefined symbol: sqliteTransientAsDestructor
note: referenced by sqlite.zig:1679 (/home/meghan/dev/.zigmod/deps/git/github.com/vrischmann/zig-sqlite/sqlite.zig:1679)
note:               /home/meghan/zig-cache/o/af79a354004d379e876ff5cb8d995080/test.o:(sqlite.DynamicStatement.bindField__anon_7594)
```

zig.mod: needs workaround.c

---

zig.mod

the `http` part is required
the `sha256-` part isnt strictly necessary but helps with caching
generated the hash with `curl -s https://sqlite.org/2025/sqlite-amalgamation-3480000.zip | sha256sum`

zig.mod: fix http dep

---

sqlite.zig

missed this case in https://github.com/vrischmann/zig-sqlite/commit/1c6938b2d28e8a758b8777aac5242ac2ef36f284

fix missed removed try in reading packed struct column
